on:
  push:
    branches: 
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install rdme@latest -g
            rdme openapi --github --version=v1.0 \
            --key=${{secrets.README_KEY}}
