name: Run npm commands on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16' # 사용하고자 하는 Node.js 버전을 설정합니다. (예: 14, 16, 18 등)
    
    # - name: Install rdme CLI
    #   run: npm install -g rdme
      
    # - name: Install dependencies
    #   run: npm install

    # - name: Run build script
    #   run: npm run build

    # - name: push file to run
    #   run:
    #     git diff --name-only HEAD~1 HEAD | grep "^src/" | while read file; do
    #       echo "$file"
    #     done

    - name: Publish OpenAPI to ReadMe
      run: |
        # For 루프를 사용하여 scripts 디렉터리에 있는 모든 파일에 대해 반복 작업 수행
        $files = Get-ChildItem -Path "src/openapi/*"
        foreach ($file in $files) {
            echo "https://github.com/shbak88/readme/blob/master/src/openapi/${file}" test!!
            # rdme openapi {https://github.com/shbak88/readme/blob/master/src/openapi/}$file.Name --key $env:README_API_KEY --update
        }
      env:
        README_API_KEY: ${{ secrets.README_KEY }}

        
